# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dla.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 688)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 0, 791, 701))
        self.stackedWidget.setObjectName("stackedWidget")
        self.equipo_page = QtWidgets.QWidget()
        self.equipo_page.setStyleSheet("background-color: #fff\n"
"")
        self.equipo_page.setObjectName("equipo_page")
        self.frame_3 = QtWidgets.QFrame(self.equipo_page)
        self.frame_3.setGeometry(QtCore.QRect(60, 160, 271, 81))
        self.frame_3.setStyleSheet("QFrame{\n"
"border: 0.5px solid #000000;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}\n"
"QFrame:hover {\n"
"border:  0.5px solid #567CF0; \n"
" }\n"
"\n"
"QFrame::hover {\n"
"border: 0.5px solid #567CF0;    \n"
"}\n"
"\n"
"                            \n"
"QFrame:focus {\n"
"border:  0.5px solid #567CF0;     \n"
" }\n"
"\n"
"QFrame:focus-within {\n"
" border: 0.5px solid #567CF0;\n"
"}\n"
"\n"
" QFrame {\n"
" box-shadow: 5px 5px 5px 5px #888888;}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_5 = QtWidgets.QFrame(self.equipo_page)
        self.frame_5.setGeometry(QtCore.QRect(350, 160, 341, 81))
        self.frame_5.setStyleSheet("QFrame{\n"
"border: 0.5px solid #000000;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}\n"
"QFrame:hover {\n"
"border:  0.5px solid #567CF0; \n"
" }\n"
"\n"
"QFrame::hover {\n"
"border: 0.5px solid #567CF0;    \n"
"}\n"
"\n"
"                            \n"
"QFrame:focus {\n"
"border:  0.5px solid #567CF0;     \n"
" }\n"
"\n"
"QFrame:focus-within {\n"
" border: 0.5px solid #567CF0;\n"
"}\n"
"\n"
" QFrame {\n"
" box-shadow: 5px 5px 5px 5px #888888;}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_4 = QtWidgets.QFrame(self.equipo_page)
        self.frame_4.setGeometry(QtCore.QRect(50, 290, 651, 261))
        self.frame_4.setStyleSheet("QFrame{\n"
"border: 0.5px solid #000000;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}\n"
"QFrame:hover {\n"
"border:  0.5px solid #567CF0; \n"
" }\n"
"\n"
"QFrame::hover {\n"
"border: 0.5px solid #567CF0;    \n"
"}\n"
"\n"
"                            \n"
"QFrame:focus {\n"
"border:  0.5px solid #567CF0;     \n"
" }\n"
"\n"
"QFrame:focus-within {\n"
" border: 0.5px solid #567CF0;\n"
"}\n"
"\n"
" QFrame {\n"
" box-shadow: 5px 5px 5px 5px #888888;\n"
"\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.framebienvenido = QtWidgets.QFrame(self.equipo_page)
        self.framebienvenido.setGeometry(QtCore.QRect(230, 50, 208, 49))
        self.framebienvenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framebienvenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framebienvenido.setObjectName("framebienvenido")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.framebienvenido)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bienvenido = QtWidgets.QLabel(self.framebienvenido)
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.bienvenido.setFont(font)
        self.bienvenido.setStyleSheet("QFrame{\n"
"font: 57 10pt \"Neue Haas Grotesk Text Pro Medi\";\n"
"}")
        self.bienvenido.setObjectName("bienvenido")
        self.horizontalLayout.addWidget(self.bienvenido)
        self.nombreUsuario = QtWidgets.QLabel(self.framebienvenido)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(11)
        self.nombreUsuario.setFont(font)
        self.nombreUsuario.setObjectName("nombreUsuario")
        self.horizontalLayout.addWidget(self.nombreUsuario)
        self.stackedWidget.addWidget(self.equipo_page)
        self.predicciones_page = QtWidgets.QWidget()
        self.predicciones_page.setObjectName("predicciones_page")
        self.frame_8 = QtWidgets.QFrame(self.predicciones_page)
        self.frame_8.setGeometry(QtCore.QRect(370, 180, 341, 81))
        self.frame_8.setStyleSheet("QFrame{\n"
"border: 0.5px solid #000000;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}\n"
"QFrame:hover {\n"
"border:  0.5px solid #567CF0; \n"
" }\n"
"\n"
"QFrame::hover {\n"
"border: 0.5px solid #567CF0;    \n"
"}\n"
"\n"
"                            \n"
"QFrame:focus {\n"
"border:  0.5px solid #567CF0;     \n"
" }\n"
"\n"
"QFrame:focus-within {\n"
" border: 0.5px solid #567CF0;\n"
"}\n"
"\n"
" QFrame {\n"
" box-shadow: 5px 5px 5px 5px #888888;}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_7 = QtWidgets.QFrame(self.predicciones_page)
        self.frame_7.setGeometry(QtCore.QRect(80, 180, 271, 81))
        self.frame_7.setStyleSheet("QFrame{\n"
"border: 0.5px solid #000000;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}\n"
"QFrame:hover {\n"
"border:  0.5px solid #567CF0; \n"
" }\n"
"\n"
"QFrame::hover {\n"
"border: 0.5px solid #567CF0;    \n"
"}\n"
"\n"
"                            \n"
"QFrame:focus {\n"
"border:  0.5px solid #567CF0;     \n"
" }\n"
"\n"
"QFrame:focus-within {\n"
" border: 0.5px solid #567CF0;\n"
"}\n"
"\n"
" QFrame {\n"
" box-shadow: 5px 5px 5px 5px #888888;}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.framebienvenido_2 = QtWidgets.QFrame(self.predicciones_page)
        self.framebienvenido_2.setGeometry(QtCore.QRect(250, 70, 208, 49))
        self.framebienvenido_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framebienvenido_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framebienvenido_2.setObjectName("framebienvenido_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.framebienvenido_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bienvenido_3 = QtWidgets.QLabel(self.framebienvenido_2)
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.bienvenido_3.setFont(font)
        self.bienvenido_3.setStyleSheet("QFrame{\n"
"font: 57 10pt \"Neue Haas Grotesk Text Pro Medi\";\n"
"}")
        self.bienvenido_3.setObjectName("bienvenido_3")
        self.horizontalLayout_3.addWidget(self.bienvenido_3)
        self.nombreUsuario_3 = QtWidgets.QLabel(self.framebienvenido_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(11)
        self.nombreUsuario_3.setFont(font)
        self.nombreUsuario_3.setObjectName("nombreUsuario_3")
        self.horizontalLayout_3.addWidget(self.nombreUsuario_3)
        self.frame_6 = QtWidgets.QFrame(self.predicciones_page)
        self.frame_6.setGeometry(QtCore.QRect(70, 310, 651, 261))
        self.frame_6.setStyleSheet("QFrame{\n"
"border: 0.5px solid #000000;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"}\n"
"QFrame:hover {\n"
"border:  0.5px solid #567CF0; \n"
" }\n"
"\n"
"QFrame::hover {\n"
"border: 0.5px solid #567CF0;    \n"
"}\n"
"\n"
"                            \n"
"QFrame:focus {\n"
"border:  0.5px solid #567CF0;     \n"
" }\n"
"\n"
"QFrame:focus-within {\n"
" border: 0.5px solid #567CF0;\n"
"}\n"
"\n"
" QFrame {\n"
" box-shadow: 5px 5px 5px 5px #888888;\n"
"\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.stackedWidget.addWidget(self.predicciones_page)
        self.subevntanas = QtWidgets.QFrame(self.centralwidget)
        self.subevntanas.setGeometry(QtCore.QRect(0, 0, 211, 781))
        self.subevntanas.setStyleSheet("background-color: rgb(198, 213, 245);")
        self.subevntanas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subevntanas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subevntanas.setObjectName("subevntanas")
        self.menu = QtWidgets.QFrame(self.subevntanas)
        self.menu.setGeometry(QtCore.QRect(0, 0, 211, 711))
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.columnaMenu = QtWidgets.QFrame(self.menu)
        self.columnaMenu.setGeometry(QtCore.QRect(10, 220, 201, 351))
        self.columnaMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.columnaMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.columnaMenu.setLineWidth(1000)
        self.columnaMenu.setMidLineWidth(1000)
        self.columnaMenu.setObjectName("columnaMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.columnaMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.botonequipo = QtWidgets.QPushButton(self.columnaMenu)
        self.botonequipo.setStyleSheet("QPushButton{\n"
"    font: 57 10pt \"Neue Haas Grotesk Text Pro Medi\";\n"
"    background-color: rgb(161, 170, 198);\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.botonequipo.setObjectName("botonequipo")
        self.verticalLayout.addWidget(self.botonequipo)
        self.botonentrenamiento = QtWidgets.QPushButton(self.columnaMenu)
        self.botonentrenamiento.setStyleSheet("QPushButton{\n"
"font: 57 10pt \"Neue Haas Grotesk Text Pro Medi\";\n"
"background-color: rgb(161, 170, 198);\n"
"border-radius: 10px;\n"
"}")
        self.botonentrenamiento.setObjectName("botonentrenamiento")
        self.verticalLayout.addWidget(self.botonentrenamiento)
        self.botonpredicciones = QtWidgets.QPushButton(self.columnaMenu)
        self.botonpredicciones.setStyleSheet("QPushButton{\n"
"font: 57 10pt \"Neue Haas Grotesk Text Pro Medi\";\n"
"background-color: rgb(161, 170, 198);\n"
"border-radius: 10px;\n"
"}")
        self.botonpredicciones.setObjectName("botonpredicciones")
        self.verticalLayout.addWidget(self.botonpredicciones)
        self.framesuperior = QtWidgets.QFrame(self.menu)
        self.framesuperior.setGeometry(QtCore.QRect(10, 30, 201, 181))
        self.framesuperior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framesuperior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framesuperior.setObjectName("framesuperior")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.framesuperior)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frametitulo = QtWidgets.QFrame(self.framesuperior)
        self.frametitulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frametitulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frametitulo.setObjectName("frametitulo")
        self.titulo = QtWidgets.QLabel(self.frametitulo)
        self.titulo.setGeometry(QtCore.QRect(0, 20, 191, 31))
        self.titulo.setMinimumSize(QtCore.QSize(191, 0))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("QFrame{\n"
"font: 57 10pt \"Neue Haas Grotesk Text Pro Medi\";\n"
"}")
        self.titulo.setObjectName("titulo")
        self.verticalLayout_2.addWidget(self.frametitulo)
        self.framelogo = QtWidgets.QFrame(self.framesuperior)
        self.framelogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framelogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framelogo.setObjectName("framelogo")
        self.logo = QtWidgets.QLabel(self.framelogo)
        self.logo.setGeometry(QtCore.QRect(40, 0, 91, 81))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/lodo_dla/foto/logo_dla-removebg-preview (3).png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.verticalLayout_2.addWidget(self.framelogo)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bienvenido.setText(_translate("MainWindow", "Bienvenido/a, "))
        self.nombreUsuario.setText(_translate("MainWindow", "TextLabel"))
        self.bienvenido_3.setText(_translate("MainWindow", "Bienvenido/a, "))
        self.nombreUsuario_3.setText(_translate("MainWindow", "TextLabel"))
        self.botonequipo.setText(_translate("MainWindow", "TU EQUIPO"))
        self.botonentrenamiento.setText(_translate("MainWindow", "ENTRENAMIENTO"))
        self.botonpredicciones.setText(_translate("MainWindow", "PREDICCIONES"))
        self.titulo.setText(_translate("MainWindow", "Dream League Assistant"))
import logo_dla_rc
